spring:
  application:
    name: intelligent-cache-servicespring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/yourdb
    username: youruser
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configurable caching policies.
caching:
  policies: LRU, LFU, Random, FIFO, MRU
  default-policy: LRU